name: example
description: Simple project to showcase the usage of flame_rive

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flame: 0.24.0
  flame_rive:
    path: ../
  flutter:
    sdk: flutter

flutter:
  uses-material-design: false
