name: flame_rive
description: Rive support for the Flame game engine. This uses the rive package and provides wrappers and components to be used inside Flame.
version: 0.0.1
homepage: https://github.com/flame-engine/flame_rive

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flame: '>=0.23.0 <1.0.0'
  rive: ^0.5.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.9.4
